### PR TITLE
Feature/scaling

### PR DESCRIPTION
**Pull request by mitchellolsthoorn**
Make it so the game scales when the screen is changed

### CODE REVIEW

**Comment by mitchellolsthoorn** [comment]
Made it so it is now possible to put the screen in fullscreen mode and changing the url of the server

**Comment by mitchellolsthoorn** [comment]
Also fixed most of the scaling bugs

**Comment by mitchellolsthoorn** [comment]
@JobEngel the shadows still have to be adapted to scale well. Could we look into this?

**Comment by mitchellolsthoorn** [comment]
@txsmith the assignment of the players to the sectors changes while scaling the first time. Could we look into this?

**Comment by newnottakenname** [comment]
Because of some problems, we have this amazing branch. We are sorry for this.

**Pull request merged**
